### ISSUE TITLE
changelog links are broken in repositories cloned over SSH

### ISSUE THREAD

**Issue by TeFiLeDo** [adamtabrams/change#13]
**Description**
When a changelog is generated, it contains several links to GitHub, utilizing the url it found via the "origin" remote. If origin is accessed via SSH, this causes the links to be something like `git@github.com:adamtabrams/change/releases/tag/0.13.3`, which isn't very usefull.

**Expection**
The script should detect whether origin is accessed over HTTPS or SSH, and if the latter, it should modify the URL accordingly.

This could be done by checking the start of the remote URL for `git@`

**Replication**
Explain how to recreate the bug.
1. Clone a repository via SSH
2. Generate a changelog using `change`
3. Check the output file

**Environment**
 - OS: Linux
 - Change Version: 0.13.3

**Further Explanation**
I _assume_ this could be changeing the first `sed` command in `update_links()` to something like:
```
sed "s|\(git@\)?\(.*\)\.git|\2|"
```

**Comment by adamtabrams** [comment]
@TeFiLeDo Thanks for finding and posting about this bug. I just released a new version to fix it. Please let me know if this fix works for your case or not.

**Comment by TeFiLeDo** [comment]
Will check this evening, ~20:00-22:00 UTC

**Comment by TeFiLeDo** [comment]
Works for me! :+1:

**Comment by adamtabrams** [comment]
Great! Thanks for the help.
