### ISSUE TITLE
Strange output running change

### ISSUE THREAD

**Issue by pylang** [adamtabrams/change#17]
**Description**
This is split from the original bug identified [elsewhere](https://github.com/adamtabrams/change/issues/12#issuecomment-835254907).

Running change on some systems may print strange output to console.  Example:

```
> git tag 0.1.0
> change init
grep: Invalid range end
grep: Invalid range end
grep: Invalid range end
grep: Invalid range end
created CHANGELOG.md
...
```

**Expection**
Clean output.

**Replication**
Explain how to recreate the bug.
1. Setup
``` 
> apt update -y && apt install git
> git config --global user.name foo
> git config --global user.email ***@***.***
> git clone https://github.com/adamtabrams/change.git
> cd change
```
2. Use command...
```
> ./run-tests
```
3. See bug
```
...
grep: Invalid range end
grep: Invalid range end
grep: Invalid range end
...
grep: Invalid range end
...
```

**Environment**
 - OS: Linux, Ubuntu focal LTS (VM)
 - Change Version: (use `change --version`)

**Further Explanation**

This problem depends on the system it is run on.  I **have not** encountered this issue on a docker install of Ubuntu focal with the same version of grep.  I **have** on other versions of Debian.

**Comment by adamtabrams** [comment]
@pylang Please post the exact output for `grep --version` for each of the systems you're using.
It seems that the current state of the issue for you is:
| System | Status | Grep Version |
|---|---|---|
| Ubuntu focal | errors | ? |
| Ubuntu (docker) | working | ? |
| Debian | errors | ? |

And the only errors you've encountered are specifically `grep: Invalid range end`

**Comment by adamtabrams** [comment]
@pylang In version 0.14.2 I made a slight change to the grep ranges. If the issues you're having are caused by locale settings, this version should fix it.

**Comment by pylang** [comment]
Success!  

- `./run-test.sh` now passes on Ubuntu-desktop and Debian-desktop.  
-  CHANGELOG.md is populated as expected without errors.

Looks like adding `[A-Za-z]` did the trick.   Many thanks!
