### ISSUE TITLE
Extra '.' added when one exists in subject.

### ISSUE THREAD

**Issue by jguiditta** [adamtabrams/change#18]
**Description**
Extra '.' added when one exists in subject.

**Expectation**
If the subject line of a commit ends with '.', an additional one should not be added.

**Replication**
Explain how to recreate the bug.
1. Add a commit that ends with '.'
2. run 'change'
3. See the new entry in changelog ends with '..'

**Environment**
 - OS: [Linux(fedora)
 - Change Version: 0.14.2

**Further Explanation**
Aside from this, the tool is quite handy and easy to use!

**Comment by adamtabrams** [comment]
@jguiditta Thanks for posting an issue! It's great to hear that this is a useful tool for you! I just pushed a [new release](https://github.com/adamtabrams/change/releases/tag/0.14.3) that only adds a period to the end of the commit message if punctuation (specifically .  ? or !) doesn't already exist. Can you verify that this update fixed the bug?

**Comment by jguiditta** [comment]
I just tested, and it seems to have fixed the issue!  Thanks so much for the quick turnaround on that.

**Comment by adamtabrams** [comment]
related changes: https://github.com/adamtabrams/change/commit/3d6ea23b2ff718162db50ffe9b05fcf45d774827
